# Complete Pytorch Tensor Tutorial (Initializing Tensors, Math, Indexing, Reshaping)

https://www.youtube.com/watch?v=x9JiIFvlUwk&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz&index=3

In [2]:
import torch
import numpy as np

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

## Initializing Tensors

In [11]:
'''
-> torch.tensor: automatically infers the dtype
-> torch.Tensor: returns the torch.FloatTensor

'''

a = torch.tensor([[1, 2, 3], [4, 5, 6]],
                 dtype=torch.float32,
                 device=device,
                 requires_grad=True)
a

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

### Common initialization methods

In [15]:
a = torch.empty(size=(2,3))
a

tensor([[8.1275e-44, 6.8664e-44, 6.7262e-44],
        [6.4460e-44, 6.7262e-44, 6.7262e-44]])

In [16]:
a = torch.zeros((2,3))
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
a = torch.rand((2,3))
a

tensor([[0.6068, 0.7009, 0.7266],
        [0.3843, 0.6084, 0.9523]])

In [19]:
a = torch.ones((2,3))
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
a = torch.eye(3)
b = torch.diag(torch.ones(3))

print(a)
print()
print(b)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [29]:
a = torch.arange(start=0, end=5, step=1)
a

tensor([0, 1, 2, 3, 4])

In [27]:
a = torch.linspace(start=0.1, end=1, steps=10)
a

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [33]:
a = torch.empty(size=(1,5)).normal_(mean=0, std=1)
b = torch.empty(size=(1,5)).uniform_(0, 1)

print(a)
print()
print(b)

tensor([[-0.1680, -0.2805, -0.8936, -0.3593,  0.4490]])

tensor([[0.7829, 0.9607, 0.3120, 0.7653, 0.1978]])


### Convert tensors to other types

In [35]:
a = torch.arange(4)
a.dtype

torch.int64

In [36]:
a.bool()

tensor([False,  True,  True,  True])

In [37]:
a.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [38]:
a.long()

tensor([0, 1, 2, 3])

In [39]:
a.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [41]:
a.float()

tensor([0., 1., 2., 3.])

In [42]:
a.float()

tensor([0., 1., 2., 3.])

### Array to tensor and vice-versa

In [45]:
np_array = np.ones((5,5))
np_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [49]:
np_array_back = tensor.numpy()
np_array_back

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Math

In [50]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

### Sum

In [52]:
z1 = torch.empty(3)
torch.add(x, y, out=z1)

z2 = torch.add(x, y)

z3 = x + y

print(z1)
print(z2)
print(z3)

tensor([5., 7., 9.])
tensor([5, 7, 9])
tensor([5, 7, 9])


### Subtraction

In [54]:
z1 = torch.empty(3)
torch.sub(x, y, out=z1)

z2 = torch.sub(x, y)

z3 = x - y

print(z1)
print(z2)
print(z3)

tensor([-3., -3., -3.])
tensor([-3, -3, -3])
tensor([-3, -3, -3])


### Division element-wise

In [58]:
z1 = torch.true_divide(x, y) # Division element-wise if the shapes matches
z1

tensor([0.2500, 0.4000, 0.5000])

### Inplace operation

In [59]:
t = torch.zeros(3)
t.add_(x)            # The underscore denotes 'inplace' operation

t

tensor([1., 2., 3.])

### Exponentiation

In [60]:
z1 = x.pow(2)

z2 = x ** 2 

print(z1)
print(z2)

tensor([1, 4, 9])
tensor([1, 4, 9])


### Comparation

In [61]:
z = x > 1

z

tensor([False,  True,  True])

### Matrix multiplication

In [67]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

x3 = torch.mm(x1, x2)   # 2x3
x4 = x1.mm(x2)

print(x3)
print()
print(x4)

tensor([[1.4689, 1.2582, 1.3447],
        [0.8092, 0.9037, 0.7241]])

tensor([[1.4689, 1.2582, 1.3447],
        [0.8092, 0.9037, 0.7241]])


### Matrix exponentiation

In [66]:
matrix_exp = torch.rand((2,2))

e1 = matrix_exp.matrix_power(2)
e2 = matrix_exp.mm(matrix_exp)

print(e1)
print()
print(e2)

tensor([[0.8147, 0.1804],
        [0.4981, 0.4039]])

tensor([[0.8147, 0.1804],
        [0.4981, 0.4039]])


### Multiplication element-wise

In [68]:
z = x * y

z

tensor([ 4, 10, 18])

### Inner product

In [69]:
z = torch.dot(x, y)

z

tensor(32)

### Batch Matrix multiplication

In [70]:
batch = 32
m = 10
n = 20
p = 30

In [71]:
t1 = torch.rand((batch, m, n))
t2 = torch.rand((batch, n, p))

In [74]:
out_bmm = torch.bmm(t1, t2) # batch x m x p

out_bmm.shape

torch.Size([32, 10, 30])

### Broadcast

Automatically expand one dimension

In [79]:
x1 = torch.ones((5,5))
x2 = torch.rand((1,5)) # Expands the row

z = x1 - x2

z

tensor([[0.6156, 0.6345, 0.1290, 0.8164, 0.8926],
        [0.6156, 0.6345, 0.1290, 0.8164, 0.8926],
        [0.6156, 0.6345, 0.1290, 0.8164, 0.8926],
        [0.6156, 0.6345, 0.1290, 0.8164, 0.8926],
        [0.6156, 0.6345, 0.1290, 0.8164, 0.8926]])

In [80]:
x1 = torch.ones((5,5))
x2 = torch.rand((5,1)) # Expands the column

z = x1 - x2

z

tensor([[0.8655, 0.8655, 0.8655, 0.8655, 0.8655],
        [0.8692, 0.8692, 0.8692, 0.8692, 0.8692],
        [0.0461, 0.0461, 0.0461, 0.0461, 0.0461],
        [0.4387, 0.4387, 0.4387, 0.4387, 0.4387],
        [0.1861, 0.1861, 0.1861, 0.1861, 0.1861]])

### Other operations

In [86]:
z = torch.rand((3,3))
z

tensor([[0.9478, 0.6076, 0.5957],
        [0.6435, 0.6603, 0.3413],
        [0.4126, 0.3527, 0.4616]])

In [87]:
values, indices = torch.max(z, dim=1) # Max in row
print(values)

values, indices = torch.max(z, dim=0) # Max in column
print(values)

tensor([0.9478, 0.6603, 0.4616])
tensor([0.9478, 0.6603, 0.5957])


In [88]:
values, indices = torch.min(z, dim=1) # Max in row
print(values)

values, indices = torch.min(z, dim=0) # Max in column
print(values)

tensor([0.5957, 0.3413, 0.3527])
tensor([0.4126, 0.3527, 0.3413])


In [89]:
ab = torch.abs(z)
ab

tensor([[0.9478, 0.6076, 0.5957],
        [0.6435, 0.6603, 0.3413],
        [0.4126, 0.3527, 0.4616]])

In [90]:
indices = torch.argmax(z, dim=1) # Max in row
print(indices)

tensor([0, 1, 2])


In [91]:
indices = torch.argmin(z, dim=1) # Max in row
print(indices)

tensor([2, 2, 1])


In [94]:
mean = torch.mean(z.float()) # Mean requires float
print(mean)

mean = torch.mean(z, dim=0)
print(mean)

tensor(0.5581)
tensor([0.6680, 0.5402, 0.4662])


In [95]:
eq = torch.eq(x, y)
eq

tensor([False, False, False])

In [99]:
sort, indices = torch.sort(y, dim=0, descending=True)
sort

tensor([6, 5, 4])

In [102]:
clamp = torch.clamp(x, min=2) # ReLU is a special case from clamp
clamp

tensor([2, 2, 3])

In [104]:
bo = torch.tensor([1,0,1,1,1], dtype=torch.bool)
an = torch.any(bo) # At least one 'True'
al = torch.all(bo) # All must be 'True'

print(an)
print(al)

tensor(True)
tensor(False)


## Indexing

In [128]:
batch_size = 10
features   = 25

x = torch.rand((batch_size, features))
y = torch.arange(10)
m = torch.tensor([0,0,0,1,1,2,2,3,4,5,5])

In [ ]:
x[0]                   # Features from first example

In [111]:
x[0].shape             # Size of feature

torch.Size([25])

In [112]:
x[:, 0]                # First feature of all examples

tensor([0.4070, 0.0574, 0.1317, 0.5332, 0.2445, 0.6893, 0.0739, 0.8842, 0.2775,
        0.1615])

In [113]:
x[0, 0:10]             # First 10 features from first example

tensor([0.4070, 0.7931, 0.3615, 0.4677, 0.7022, 0.1779, 0.5076, 0.0333, 0.2799,
        0.0994])

In [114]:
x[0, 0] = 100          # Assign a value

In [116]:
indices = [2, 5, 6]
y[indices]

tensor([2, 5, 6])

In [118]:
rows = torch.tensor([0,1])
cols = torch.tensor([2,3])

x[rows, cols]          # x[0,2] and x[1,3]

tensor([0.4203, 0.9912])

In [122]:
y[(y < 2) | (y > 8)]

tensor([0, 1, 9])

In [124]:
y[(y > 2) & (y < 8)]

tensor([3, 4, 5, 6, 7])

In [125]:
y[(y.remainder(2)) == 0]

tensor([0, 2, 4, 6, 8])

In [127]:
torch.where(y > 5, y, 0)

tensor([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [129]:
m.unique()

tensor([0, 1, 2, 3, 4, 5])

In [130]:
x.ndimension()

2

In [131]:
x.numel()

250

## Reshape

In [21]:
x = torch.arange(9)
y = torch.rand((2,5))
z = torch.rand((2,5))
b = torch.rand((64, 2, 5))

In [9]:
x1 = x.view(3,3)
print(x1)

x2 = x.reshape(3,3)  # Always gonna work, but cause a performance loss
print(x2)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [10]:
x3 = x1.t()
x3

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [17]:
x4 = torch.cat((y, z), dim=0)
x4.shape

torch.Size([4, 5])

In [19]:
x5 = y.view(-1)
x5

tensor([0.4543, 0.0950, 0.4970, 0.3040, 0.4360, 0.3302, 0.5149, 0.0953, 0.7802,
        0.1158])

In [24]:
x6 = b.view(64, -1)
x6.shape

torch.Size([64, 10])

In [26]:
x7 = x1.permute(1, 0)
x7

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [29]:
x8 = x.unsqueeze(0)
x8.shape

torch.Size([1, 9])

In [30]:
x9 = x8.squeeze(0)
x9.shape

torch.Size([9])